# ------------------------ #
# True auxiliary variables #
# ------------------------ #

[[aux]]
private_name = "time"
long_name = "time"

[[aux]]
private_name = "year"
long_name = "year"

[[aux]]
private_name = "day"
long_name = "day of year"

[[aux]]
private_name = "prior_altitude"
long_name = "altitude a.s.l."

[[aux]]
private_name = "hour"
long_name = "UTC hour"

[[aux]]
private_name = "lat"
long_name = "latitude"

[[aux]]
private_name = "long"
long_name = "longitude"

[[aux]]
private_name = "zobs"
long_name = "observation altitude"

[[aux]]
private_name = "zmin"
long_name = "pressure altitude"

[[aux]]
private_name = "solzen"
long_name = "solar zenith angle"

[[aux]]
private_name = "azim"
long_name = "solar azimuth angle"

[[aux]]
private_name = "tout"
long_name = "atmospheric temperature near surface"

[[aux]]
private_name = "pout"
long_name = "surface pressure"

[[aux]]
private_name = "hout"
long_name = "atmospheric humidity near surface"

[[aux]]
private_name = "sia"
long_name = "average solar intensity"

[[aux]]
private_name = "fvsi"
long_name = "fractional variation in solar intensity"

[[aux]]
private_name = "wspd"
long_name = "wind speed"

[[aux]]
private_name = "wdir"
long_name = "wind direction"

[[aux]]
private_name = "o2_mean_mole_fraction"
long_name = "global mean dry atmospheric mole fraction of oxygen"

[[aux]]
private_name = "integration_operator"
long_name = "integration operator"

[[aux]]
private_name = "o2_7885_am_o2"
public_name = "airmass"
long_name = "airmass"
attr_overrides = { units = "1", description = "airmass computed as the total vertical column of O2 divided by the total slant column of O2 retrieved from the window centered at 7885 cm-1." }


#---------------------------------#
# Additional a priori information #
#---------------------------------#

[[computed]]
type = "prior_source"

[[extra_priors]]
private_name = "prior_time"
long_name = "time of a priori data"

[[extra_priors]]
private_name = "prior_density"
long_name = "a priori number density of air"

[[extra_priors]]
private_name = "prior_effective_latitude"
long_name = "a priori effective latitude"

[[extra_priors]]
private_name = "prior_equivalent_latitude"
long_name = "a priori equivalent latitude"
attr_overrides = { description = "equivalent latitude derived from potential voriticity on potential temperature levels" }

[[extra_priors]]
private_name = "prior_gravity"
long_name = "a priori gravitational acceleration"

[[extra_priors]]
private_name = "prior_mid_tropospheric_potential_temperature"
long_name = "a priori mid-tropospheric potential temperature"

[[extra_priors]]
private_name = "prior_pressure"
long_name = "a priori atmospheric pressure"

[[extra_priors]]
private_name = "prior_temperature"
long_name = "a priori atmospheric temperature"

[[extra_priors]]
private_name = "prior_tropopause_altitude"
long_name = "a priori tropopause altitude"

# ------------------------------------- #
# Additional specific variables to copy #
# ------------------------------------- #

[[aux]]
private_name = "xn2o_original"
long_name = "column average nitrous oxide mole fraction"
attr_to_remove = [
    "standard_name",
    "precision",
    "note",
] # incorporated the note about the T-dependent bias reduction into the overridden description.
[aux.attr_overrides]
wmo_or_analogous_scale = "NOAA 2006A"
description = "o2_mean_mole_fraction * column_n2o / column_o2. This variable contains the XN2O values BEFORE the temperature bias reduction is applied but AFTER the new O2 mole fractions were applied. Most users should prefer the 'xn2o' variable over this one."

[[aux]]
private_name = "column_o2"
long_name = "oxygen column density"
[aux.attr_overrides]
description = "column density of oxygen retrieved from the singlet-delta band"
note = "Use the o2_mean_mole_fraction variable to convert to a column of dry air if needed, e.g., for calculation of surface pressure."
ancillary_variables = "o2_mean_mole_fraction"

[[aux]]
private_name = "column_o2_error"
long_name = "oxygen column density error"
[aux.attr_overrides]
description = "one-sigma precision"

[[aux]]
private_name = "o2_7885_ovc_o2"
public_name = "prior_column_o2"
long_name = "a priori oxygen column density"
[aux.attr_overrides]
description = "Column density calculated from the PRIOR of oxygen"
units = "molecules.cm-2"

# ------------------------------------------------------------------- #
# Xgases with non-default names or special considerations for copying #
# ------------------------------------------------------------------- #

[[xgas]]
xgas = "xluft"
gas = "luft"
gas_long = "dry air"
prior_profile = { type = "omit" }
prior_xgas = { type = "omit" }
ak = { type = "omit" }

[[xgas]]
xgas = "xco"
gas = "co"
xgas_attr_overrides = { wmo_or_analogous_scale = "Not used" }

# -------------- #
# Other settings #
# -------------- #

[discovery]
excluded_gases = ["th2o", "fco2", "zco2"]
excluded_xgas_variables = ["xo2"]

