[mappings.std_names]
prior_temperature = "air_temperature"
prior_pressure = "air_pressure"
prior_density = "number_concentration_of_air"
prior_gravity = "gravity"
prior_equivalent_latitude = "equivalent_latitude_derived_from_potential_vorticity"
prior_effective_latitude = "effective_latitude_derived_from_mid_troposphere_potential_temperature"
prior_mid_tropospheric_potential_temperature = "prior_mid_tropospheric_potential_temperature"


# Each of these section indicates that we need to copy:
#   1. x{specie}
#   2. x{specie}_error
#   3. ak_x{specie}
#   4. extrapolation_flags_ak_x{specie}
#   5. prior_{specie} or prior_{prior_gas} if given
#   6. prior_x{specie} or prior_x{prior_gas} if given
# This ensures that all the variables needed for a given gas are included.
# This will also ensure that the xgas values, priors xgas values, and prior profiles
# are converted to the same units.

[[gases]]
specie = "co2"
public_units = "ppm"
standard_name = "carbon_dioxide"
wmo_scale = "WMO CO2 X2007"

[[gases]]
specie = "wco2"
public_units = "ppm"
standard_name = "carbon_dioxide_from_weak_band"
wmo_scale = "WMO CO2 X2007"
prior_gas = "co2"
add_xgas_attributes = {description = "0.2095*column_wco2/column_o2, this is the weak CO2 band centered at 6073.5 and does not contribute to the xco2 calculation."}
experimental = true

[[gases]]
specie = "lco2"
public_units = "ppm"
standard_name = "carbon_dioxide_from_strong_band"
wmo_scale = "WMO CO2 X2007"
prior_gas = "co2"
add_xgas_attributes = {description = "0.2095*column_lco2/column_o2, this is the strong CO2 band centered at 6073.5 and does not contribute to the xco2 calculation."}
experimental = true

[[gases]]
specie = "co2_x2019"
public_units = "ppm"
standard_name = "carbon_dioxide"
wmo_scale = "WMO CO2 X2019"

[[gases]]
specie = "wco2_x2019"
public_units = "ppm"
standard_name = "carbon_dioxide_from_weak_band"
wmo_scale = "WMO CO2 X2019"
prior_gas = "co2"
add_xgas_attributes = {description = "0.2095*column_wco2/column_o2, this is the weak CO2 band centered at 6073.5 and does not contribute to the xco2 calculation."}
experimental = true

[[gases]]
specie = "lco2_x2019"
public_units = "ppm"
standard_name = "carbon_dioxide_from_strong_band"
wmo_scale = "WMO CO2 X2019"
prior_gas = "co2"
add_xgas_attributes = {description = "0.2095*column_lco2/column_o2, this is the strong CO2 band centered at 6073.5 and does not contribute to the xco2 calculation."}
experimental = true

[[gases]]
specie = "ch4"
public_units = "ppm"
standard_name = "methane"
wmo_scale = "WMO CH4 2004"

[[gases]]
specie = "co"
public_units = "ppb"
standard_name = "carbon_monoxide"
wmo_scale = "Not used"

[[gases]]
specie = "n2o"
public_units = "ppb"
standard_name = "nitrous_oxide"
wmo_scale = "NOAA 2006A"

[[gases]]
specie = "hf"
public_units = "ppt"
standard_name = "hydrogen_fluoride"
wmo_scale = "N/A"

[[gases]]
specie = "h2o"
public_units = "ppm"
standard_name = "water"
wmo_scale = "ARM Radiosondes (Lamont+Darwin)"

[[gases]]
specie = "hdo"
public_units = "ppm"
standard_name = "semiheavy_water"
wmo_scale = "N/A"

[[gases]]
specie = "xluft"
public_units = "1"
standard_name = "air"
prior_gas = "o2"
has_aks = false


# Then we define other variables that we want to copy but which aren't automatically included with the gas variables.
[[ancillary_variables]]
private_names = ["prior_temperature", "prior_pressure", "prior_gravity", "prior_equivalent_latitude", "prior_effective_latitude", "prior_mid_tropospheric_potential_temperature"]
public_names = "{name}"

[[ancillary_variables]]
private_name = "prior_density"
public_name = "prior_density"
add_attributes = {note = "This is the ideal number density for the temperature and pressure at each model level. GGG assumes that this includes water, and so multiplies this by wet mole fractions of trace gases to get those gases' number densities."}

[[ancillary_variables]]
private_names = ["gfit_version", "gsetup_version", "year", "day", "hour", "lat", "long", "time", "zobs", "zmin", "solzen", "azim", "tout", "pout", "hout", "sia", "fvsi", "wspd", "wdir"]

[[ancillary_variables]]
private_name = "o2_7885_am_o2"
public_name = "airmass"
long_name = "airmass"
units = "1"

[[ancillary_variables]]
private_name = "integration_operator"
public_name = "{name}"
add_attributes = {relates_to = "xluft, xhf, xh2o, xhdo, xco, xn2o, xch4, xco2, xwco2_experimental, xlco2_experimental", usage = "https://tccon-wiki.caltech.edu/Main/AuxiliaryDataGGG2020"}

[[ancillary_variables]]
private_name = "integration_operator_x2019"
public_name = "{name}"
add_attributes = {relates_to = "xco2_x2019, xwco2_experimental_x2019, xlco2_experimental_x2019", usage = "https://tccon-wiki.caltech.edu/Main/AuxiliaryDataGGG2020"}