[book]
authors = ["Joshua Laughner"]
language = "en"
multilingual = false
src = "src"
title = "GGG-RS User Guide"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/TCCON/ggg-rs"
fold = { enable = true, level = 2 }
