# !! All actions used should pin to a specific commit to reduce
# !! vulnerability to a supply chain attack
name: Run cargo tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Pinned to v6.0.2 commit on 26 Mar 2026
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
